# Auto-generated by housekeep 2026-06-26.
# Removes the stale confident-payne-160e1a worktree directory after the
# Claude Code session that was running inside it closes.
# Run once from any terminal: .\cleanup-confident-payne-worktree.ps1
$target = "C:\Projects\eq-cards\.claude\worktrees\confident-payne-160e1a"
if (Test-Path $target) {
    Remove-Item -Recurse -Force $target
    Write-Host "Removed $target"
    Remove-Item -Force $PSCommandPath
    Write-Host "Removed this script."
} else {
    Write-Host "$target already gone."
    Remove-Item -Force $PSCommandPath
}
